# Generated by Django 5.1.4 on 2025-01-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_remove_mobile_description_mobile_back_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='url',
            new_name='image_url',
        ),
    ]
